/* Generado automáticamente desde Goodreads con herramientas/actualizar_libros.py.
   No hace falta editarlo a mano. */
window.LIBROS = [
{
"t": "People in Love",
"a": "Claire Daverley",
"s": 0,
"y": 2026,
"p": 366,
"i": 214936982,
"c": 0,
"d": "2026-09-27",
"o": 2026,
"e": "Penguin"
},
{
"t": "El jardín italiano",
"a": "Alyson Richman",
"s": 4,
"y": 2026,
"p": 432,
"i": 60858408,
"c": 1,
"d": "2026-09-12",
"o": 2014,
"e": "Espasa"
},
{
"t": "No hablemos más de amor",
"a": "Le Tellier Hervé",
"s": 3,
"y": 2026,
"p": 232,
"i": 10378541,
"c": 1,
"d": "2026-09-05",
"o": 2009,
"e": "GRIJALBO"
},
{
"t": "Las intermitencias de la muerte",
"a": "José Saramago",
"s": 4,
"y": 2026,
"p": 274,
"i": 2543,
"c": 1,
"d": "2026-08-30",
"o": 2005,
"e": "Alfaguara"
},
{
"t": "Death and the Gardener",
"a": "Georgi Gospodinov",
"s": 4,
"y": 2026,
"p": 224,
"i": 223736245,
"c": 1,
"d": "2026-08-02",
"o": 2024,
"e": "Liveright"
},
{
"t": "Monetízate",
"a": "Andrés Pérez Ortega",
"s": 3,
"y": 2026,
"p": 347,
"i": 43697166,
"c": 0,
"d": "2026-07-26",
"o": 2019,
"e": "Alienta Editorial"
},
{
"t": "Demon Copperhead",
"a": "Barbara Kingsolver",
"s": 5,
"y": 2026,
"p": 560,
"i": 60194162,
"c": 1,
"d": "2026-07-22",
"o": 2022,
"e": "Harper"
},
{
"t": "Los espantos de mamá",
"a": "Gilmer Mesa",
"s": 4,
"y": 2026,
"p": 296,
"i": 239879680,
"c": 0,
"d": "2026-07-20",
"o": 2025,
"e": "Literatura Random House"
},
{
"t": "The Lost Bookshop",
"a": "Evie Woods",
"s": 3,
"y": 2026,
"p": 444,
"i": 65137920,
"c": 1,
"d": "2026-06-16",
"o": 2023,
"e": "One More Chapter/HarperCollins UK"
},
{
"t": "Aranjuez",
"a": "Gilmer Mesa",
"s": 4,
"y": 2026,
"p": 296,
"i": 198388884,
"c": 0,
"d": "2026-05-03",
"o": 2023,
"e": "RANDOM HOUSE"
},
{
"t": "Control",
"a": "Freddy Vega",
"s": 4,
"y": 2026,
"p": 304,
"i": 250325342,
"c": 0,
"d": "2026-04-25",
"o": 2026,
"e": "EDICIONES B"
},
{
"t": "Actos humanos",
"a": "Han Kang",
"s": 0,
"y": 2026,
"p": 272,
"i": 39354030,
"c": 1,
"d": "2026-04-21",
"o": 2014,
"e": "Rata Books"
},
{
"t": "Cómo controlar el pensamiento excesivo",
"a": "Harvard Business Review",
"s": 0,
"y": 2026,
"p": 100,
"i": 237148432,
"c": 0,
"d": "2026-03-11",
"o": 2025,
"e": "Reverte-Management"
},
{
"t": "Todo sobre el amor",
"a": "bell hooks",
"s": 3,
"y": 2026,
"p": 238,
"i": 51417,
"c": 1,
"d": "2026-03-03",
"o": 1999,
"e": "Vergara Editor S.A."
},
{
"t": "El camino del artista",
"a": "Julia Cameron",
"s": 3,
"y": 2026,
"p": 316,
"i": 37758372,
"c": 1,
"d": "2026-02-21",
"o": 2002,
"e": "Aguilar (Penguin Random House)"
},
{
"t": "Verity",
"a": "Colleen Hoover",
"s": 0,
"y": 2026,
"p": 336,
"i": 59344312,
"c": 1,
"d": "2026-01-21",
"o": 2018,
"e": "Grand Central Publishing"
},
{
"t": "Los siete maridos de Evelyn Hugo",
"a": "Taylor Jenkins Reid",
"s": 0,
"y": 2026,
"p": 384,
"i": 52061530,
"c": 1,
"d": "2026-01-18",
"o": 2017,
"e": "Umbriel"
},
{
"t": "The Long Game",
"a": "Rachel Reid",
"s": 4,
"y": 2025,
"p": 479,
"i": 58939872,
"c": 1,
"d": "2025-12-22",
"o": 2022,
"e": "Carina Press"
},
{
"t": "Heated Rivalry",
"a": "Rachel Reid",
"s": 4,
"y": 2025,
"p": 375,
"i": 41735449,
"c": 1,
"d": "2025-12-22",
"o": 2019,
"e": "Carina Press"
},
{
"t": "Beach Read",
"a": "Emily Henry",
"s": 4,
"y": 2025,
"p": 358,
"i": 52867387,
"c": 1,
"d": "2025-11-24",
"o": 2020,
"e": "Berkley"
},
{
"t": "Heart the Lover",
"a": "Lily King",
"s": 4,
"y": 2025,
"p": 256,
"i": 228110489,
"c": 1,
"d": "2025-11-14",
"o": 2025,
"e": "Grove Press"
},
{
"t": "La mujer incierta",
"a": "Piedad Bonnett",
"s": 3,
"y": 2025,
"p": 234,
"i": 217921332,
"c": 0,
"d": "2025-11-03",
"o": 2024,
"e": "ALFAGUARA"
},
{
"t": "Deep End",
"a": "Ali Hazelwood",
"s": 4,
"y": 2025,
"p": 464,
"i": 212808709,
"c": 1,
"d": "2025-11-01",
"o": 2025,
"e": "Berkley"
},
{
"t": "Cómo tratar con gente difícil",
"a": "Harvard Business Review",
"s": 5,
"y": 2025,
"p": 150,
"i": 51044249,
"c": 1,
"d": "2025-08-20",
"o": 2007,
"e": "EDITORIAL REVERTE SA",
"r": "Estos libros de Harvard business review me han parecido excelentes. Concisos, prácticos y con ejemplos para mejorar en habilidades blandas. Se los recomiendo mucho"
},
{
"t": "Nuestra parte de noche",
"a": "Mariana Enriquez",
"s": 5,
"y": 2025,
"p": 672,
"i": 48758708,
"c": 1,
"d": "2025-08-13",
"o": 2019,
"e": "Anagrama"
},
{
"t": "Steal Like an Artist",
"a": "Austin Kleon",
"s": 4,
"y": 2025,
"p": 160,
"i": 13099738,
"c": 1,
"d": "2025-07-02",
"o": 2012,
"e": "Workman Publishing Company"
},
{
"t": "Liderazgo",
"a": "Harvard Business Review",
"s": 4,
"y": 2025,
"p": 150,
"i": 51092357,
"c": 1,
"d": "2025-07-02",
"o": 2019,
"e": "EDITORIAL REVERTE SA"
},
{
"t": "A Gentleman in Moscow",
"a": "Amor Towles",
"s": 5,
"y": 2025,
"p": 495,
"i": 34066798,
"c": 1,
"d": "2025-06-07",
"o": 2016,
"e": "Penguin Books"
},
{
"t": "Resiliência",
"a": "Harvard Business Review",
"s": 5,
"y": 2025,
"p": 93,
"i": 53194774,
"c": 1,
"d": "2025-05-15",
"o": 2017,
"e": "Editora Sextante"
},
{
"t": "Guías HBR",
"a": "Various",
"s": 5,
"y": 2025,
"p": 272,
"i": 43735959,
"c": 1,
"d": "2025-05-04",
"o": 2018,
"e": "Reverté Management International",
"r": "A todos nos surge en algún punto de nuestra carrera profesional el querer mejorar, y no solo técnicamente hablando sino en las otras habilidades que últimamente están en boca de todos: liderazgo, comunicación, gestión emocional, toma de decisiones, etc.  \n\nY es que sucede que tenemos una opinión sesgada de como nos deberíamos comportar, como deberían actuar los demás, como gestionamos las emociones y las de los demás, como comunicar, como tomar decisiones y un largo etc. \n\nUnos no se dan cuenta y siguen “batallando” lo que venga como se pueda, creyendo tener la veracidad para hacerlo. \n\nOtros buscan ayuda con amigos para reafirmar lo que piensan o para recibir consejos que aplican. \n\nOtros  leen libros y los ponen en practica o buscan coach porque su puesto es importante y quieren hacer su mejor rol. \n\nPor mi parte, voy reconociendo mis “errores” y siendo consciente de ellos. \n\nY sí, es difícil. Porque uno quiere cambiar TODO de una vez \n\ny pues así no funcionan los hábitos o las habilidades.  \n\nEspero que uds también estén las mismas. Pensemos que pasamos 8 o mas horas haciendo nuestro trabajo, qué mejor que hacerlo cada vez mejor."
},
{
"t": "The Maniac",
"a": "Benjamín Labatut",
"s": 5,
"y": 2025,
"p": 368,
"i": 75665931,
"c": 1,
"d": "2025-04-28",
"o": 2023,
"e": "Penguin Press",
"r": "Ultimamente Labatut se ha convertido en mi favorito. \n\nY es que escribir sobre sucesos científicos desde una perspectiva humana es muy difícil y él lo hace genial. (o al menos para mi). \n\nEl nombre de Maniac no solo abarca las siglas del computador sino también la conducta de los grandes científicos ahí descritos. Su hilo de pensamiento. El libro me permitió leer con un estilo de entrevistas de momentos que pasaron con von Neumann; el impacto que tuvo en ellos. La verdad que no magnificaba el alcance de él en el mundo del ahora. Es curioso como el pasar de los años hace estragos en la memoria histórica. \n\nEn fin, un gran libro. Muy recomendado."
},
{
"t": "Autoconciencia",
"a": "Daniel Goleman",
"s": 5,
"y": 2025,
"p": 192,
"i": 49184957,
"c": 1,
"d": "2025-03-20",
"o": 2020,
"e": "Reverté Management International"
},
{
"t": "La psicología del dinero",
"a": "Morgan Housel",
"s": 4,
"y": 2025,
"p": 312,
"i": 61338803,
"c": 1,
"d": "2025-03-14",
"o": 2020,
"e": "Planeta"
},
{
"t": "¡Es la microbiota, idiota!",
"a": "Sari Arponen",
"s": 3,
"y": 2025,
"p": 368,
"i": 57292401,
"c": 1,
"d": "2025-02-23",
"o": 2021,
"e": "Alienta Editorial"
},
{
"t": "La mala costumbre",
"a": "Alana S. Portero",
"s": 5,
"y": 2025,
"p": 252,
"i": 123723946,
"c": 1,
"d": "2025-02-13",
"o": 2023,
"e": "Seix Barral"
},
{
"t": "Los cuatro acuerdos",
"a": "Miguel Ruiz",
"s": 3,
"y": 2025,
"p": 168,
"i": 6600,
"c": 1,
"d": "2025-02-10",
"o": 1997,
"e": "Amber-Allen Publishing"
},
{
"t": "Azami, el club de Mitsuko",
"a": "Aki Shimazaki",
"s": 4,
"y": 2025,
"p": 176,
"i": 122777503,
"c": 1,
"d": "2025-02-05",
"o": 2014,
"e": "Nórdica Libros"
},
{
"t": "En la Tierra somos fugazmente grandiosos",
"a": "Ocean Vuong",
"s": 3,
"y": 2024,
"p": 263,
"i": 49360952,
"c": 1,
"d": "2024-11-04",
"o": 2019,
"e": "Anagrama"
},
{
"t": "Book Lovers",
"a": "Emily Henry",
"s": 5,
"y": 2024,
"p": 377,
"i": 58690308,
"c": 1,
"d": "2024-09-22",
"o": 2022,
"e": "Berkley"
},
{
"t": "Poeta chileno",
"a": "Alejandro Zambra",
"s": 4,
"y": 2024,
"p": 421,
"i": 50272339,
"c": 1,
"d": "2024-08-17",
"o": 2020,
"e": "Anagrama"
},
{
"t": "It Ends with Us",
"a": "Colleen Hoover",
"s": 4,
"y": 2024,
"p": 386,
"i": 27362503,
"c": 1,
"d": "2024-08-11",
"o": 2016,
"e": "Atria Books"
},
{
"t": "El invencible verano de Liliana",
"a": "Cristina Rivera Garza",
"s": 3,
"y": 2024,
"p": 304,
"i": 57937068,
"c": 1,
"d": "2024-06-22",
"o": 2021,
"e": "Literatura Random House",
"r": "Sé que el libro tiene muchos premios y que la historia es importante y toca temas relevantes como el feminicidio. Sin embargo, lo encontré poco profundo, inconcluso en la búsqueda de la escritora/hermana. \n\nVale la pena leerlo porque es importante hablar sobre este tema y también hablar sobre Liliana. Pero queda un sin sabor, un faltó más."
},
{
"t": "Lecciones de química",
"a": "Bonnie Garmus",
"s": 4,
"y": 2024,
"p": 464,
"i": 65041842,
"c": 0,
"d": "2024-05-25",
"o": 2022,
"e": "Salamandra"
},
{
"t": "Contradeseo",
"a": "Gloria Susana Esquivel",
"s": 0,
"y": 2024,
"p": 240,
"i": 197901934,
"c": 0,
"d": "2024-03-28",
"o": 2023,
"e": "Literatura Random House"
},
{
"t": "El libro del duelo",
"a": "Ricardo Silva Romero",
"s": 4,
"y": 2024,
"p": 237,
"i": 198388871,
"c": 0,
"d": "2024-02-29",
"o": 2023,
"e": "Alfaguara"
},
{
"t": "Exhalation",
"a": "Ted Chiang",
"s": 4,
"y": 2024,
"p": 32,
"i": 48588075,
"c": 1,
"d": "2024-02-25",
"o": 2009,
"e": "Night Shade Books"
},
{
"t": "La hija única",
"a": "Guadalupe Nettel",
"s": 4,
"y": 2023,
"p": 240,
"i": 55152903,
"c": 1,
"d": "2023-11-30",
"o": 2020,
"e": "Anagrama"
},
{
"t": "Men Without Women",
"a": "Haruki Murakami",
"s": 3,
"y": 2023,
"p": 242,
"i": 33652490,
"c": 1,
"d": "2023-11-05",
"o": 2014,
"e": "Bond Street Books"
},
{
"t": "Stuck with You",
"a": "Ali Hazelwood",
"s": 4,
"y": 2023,
"p": 127,
"i": 59651555,
"c": 0,
"d": "2023-09-17",
"o": 2022,
"e": "Berkley"
},
{
"t": "After Dark",
"a": "Haruki Murakami",
"s": 4,
"y": 2023,
"p": 191,
"i": 17803,
"c": 1,
"d": "2023-09-09",
"o": 2004,
"e": "Knopf"
},
{
"t": "Carta de una desconocida",
"a": "Stefan Zweig",
"s": 4,
"y": 2023,
"p": 72,
"i": 45732,
"c": 1,
"d": "2023-07-03",
"o": 1922,
"e": "Acantilado"
},
{
"t": "Before We Were Strangers",
"a": "Renee Carlino",
"s": 0,
"y": 2023,
"p": 310,
"i": 23309634,
"c": 1,
"d": "2023-06-12",
"o": 2015,
"e": "Atria Books"
},
{
"t": "La forma de las ruinas",
"a": "Juan Gabriel Vásquez",
"s": 4,
"y": 2023,
"p": 560,
"i": 27843845,
"c": 1,
"d": "2023-06-11",
"o": 2015,
"e": "Alfaguara"
},
{
"t": "Magníficos rebeldes",
"a": "Andrea Wulf",
"s": 5,
"y": 2023,
"p": 496,
"i": 63254628,
"c": 1,
"d": "2023-05-14",
"o": 2022,
"e": "Taurus"
},
{
"t": "What I Talk About When I Talk About Running",
"a": "Haruki Murakami",
"s": 4,
"y": 2023,
"p": 188,
"i": 2195464,
"c": 1,
"d": "2023-03-26",
"o": 2007,
"e": "Knopf Publishing Group"
},
{
"t": "El hombre en busca de sentido",
"a": "Viktor E. Frankl",
"s": 3,
"y": 2023,
"p": 157,
"i": 1087293,
"c": 1,
"d": "2023-03-19",
"o": 1946,
"e": "Herder Editorial"
},
{
"t": "Las primas",
"a": "Aurora Venturini",
"s": 3,
"y": 2023,
"p": 153,
"i": 55996937,
"c": 1,
"d": "2023-01-23",
"o": 2007,
"e": "TusQuets Argentina"
},
{
"t": "El ruido de las cosas al caer",
"a": "Juan Gabriel Vásquez",
"s": 4,
"y": 2023,
"p": 273,
"i": 19346279,
"c": 1,
"d": "2023-01-10",
"o": 2011,
"e": "ALFAGUARA"
},
{
"t": "The Personal Librarian",
"a": "Marie Benedict",
"s": 4,
"y": 2023,
"p": 341,
"i": 55333938,
"c": 1,
"d": "2023-01-04",
"o": 2021,
"e": "Berkley Books"
},
{
"t": "Eleanor Oliphant Is Completely Fine",
"a": "Gail Honeyman",
"s": 5,
"y": 2022,
"p": 390,
"i": 35900387,
"c": 1,
"d": "2022-12-08",
"o": 2017,
"e": "HarperCollins GB",
"r": "No me gustó hasta que me gustó!"
},
{
"t": "A hipótese do amor: Capítulo Extra",
"a": "Ali Hazelwood",
"s": 4,
"y": 2022,
"p": 34,
"i": 62338959,
"c": 1,
"d": "2022-10-28",
"o": 2022,
"e": "Arqueiro",
"r": "4 estrellas por el simple hecho de que soy científica y leer una historia ambientada en este mundo insufrible es chevere. No esperen que sea el próximo premio nobel, pero lo encontré divertido y muy rápido de leer.\n\nUna cosa si me gustó y es que Ali habla de las cosas negativas del quehacer científico; rivalidades entre colegas, esa superioridad de los profesores o directores de tesis, los malos salarios y las extenuantes jornadas para obtener resultados \"decentes\". Así que si trabajan en las ciencias y si son mujeres creo que lo encontrarán divertido de leer, pero repito, no esperen más que eso."
},
{
"t": "Love on the Brain",
"a": "Ali Hazelwood",
"s": 4,
"y": 2022,
"p": 368,
"i": 59571699,
"c": 1,
"d": "2022-10-24",
"o": 2022,
"e": "Sphere"
},
{
"t": "El libro de mi destino",
"a": "Parinoush Saniee",
"s": 4,
"y": 2022,
"p": 448,
"i": 22852800,
"c": 1,
"d": "2022-10-21",
"o": 2002,
"e": "Salamandra"
},
{
"t": "In Emergency, Break Glass",
"a": "Nate Anderson",
"s": 3,
"y": 2022,
"p": 208,
"i": 58999200,
"c": 1,
"d": "2022-10-16",
"o": 2022,
"e": "W. W. Norton & Company"
},
{
"t": "The Midnight Library",
"a": "Matt Haig",
"s": 5,
"y": 2022,
"p": 288,
"i": 52578297,
"c": 1,
"d": "2022-10-16",
"o": 2020,
"e": "Viking"
},
{
"t": "Dark Matter",
"a": "Blake Crouch",
"s": 5,
"y": 2022,
"p": 342,
"i": 27833670,
"c": 1,
"d": "2022-10-02",
"o": 2016,
"e": "Ballantine Books"
},
{
"t": "Un verdor terrible",
"a": "Benjamín Labatut",
"s": 5,
"y": 2022,
"p": 213,
"i": 55756916,
"c": 1,
"d": "2022-08-17",
"o": 2020,
"e": "Editorial Anagrama"
},
{
"t": "La bailarina de Auschwitz",
"a": "Edith Eger",
"s": 5,
"y": 2022,
"p": 416,
"i": 40520204,
"c": 1,
"d": "2022-08-07",
"o": 2017,
"e": "Planeta"
},
{
"t": "En defensa del humanismo",
"a": "Alejandro Gaviria",
"s": 3,
"y": 2022,
"p": 118,
"i": 58858519,
"c": 0,
"d": "2022-07-27",
"o": 2021,
"e": "Ariel Colombia"
},
{
"t": "The Power",
"a": "Naomi Alderman",
"s": 5,
"y": 2022,
"p": 400,
"i": 29751398,
"c": 1,
"d": "2022-07-20",
"o": 2016,
"e": "Viking"
},
{
"t": "Las malas",
"a": "Camila Sosa Villada",
"s": 5,
"y": 2022,
"p": 224,
"i": 44438256,
"c": 1,
"d": "2022-07-18",
"o": 2019,
"e": "Tusquets"
},
{
"t": "La disolución",
"a": "Diego Erlan",
"s": 2,
"y": 2022,
"p": 216,
"i": 33117509,
"c": 1,
"d": "2022-07-04",
"o": 2016,
"e": "Tusquets"
},
{
"t": "A Burning",
"a": "Megha Majumdar",
"s": 3,
"y": 2022,
"p": 304,
"i": 51792100,
"c": 1,
"d": "2022-06-20",
"o": 2020,
"e": "Knopf"
},
{
"t": "Fragmentos de amor furtivo",
"a": "Héctor Abad Faciolince",
"s": 5,
"y": 2022,
"p": 368,
"i": 2178713,
"c": 1,
"d": "2022-06-06",
"o": 2011,
"e": "Alfaguara"
},
{
"t": "El principito",
"a": "El Gato de Hojalata",
"s": 3,
"y": 2022,
"p": 0,
"i": 31559252,
"c": 1,
"d": "2022-04-17",
"o": 2016,
"e": "El gato de hojalata"
},
{
"t": "Esta herida llena de peces",
"a": "Lorena Salazar Masso",
"s": 3,
"y": 2022,
"p": 168,
"i": 57028232,
"c": 1,
"d": "2022-04-11",
"o": 2021,
"e": "Tránsito"
},
{
"t": "La sombra de mi padre",
"a": "Martín Franco Velez",
"s": 5,
"y": 2022,
"p": 152,
"i": 55166720,
"c": 0,
"d": "2022-04-06",
"o": 2020,
"e": "Planeta Colombia"
},
{
"t": "Her Hidden Genius",
"a": "Marie Benedict",
"s": 5,
"y": 2022,
"p": 284,
"i": 58108269,
"c": 0,
"d": "2022-03-28",
"o": 2022,
"e": "Sourcebooks Landmark"
},
{
"t": "The Other Einstein",
"a": "Marie Benedict",
"s": 5,
"y": 2022,
"p": 304,
"i": 28389305,
"c": 1,
"d": "2022-03-20",
"o": 2016,
"e": "Sourcebooks Landmark",
"r": "Creo que alcancé a odiar a Eisntein durante gran parte del libro y lo culpé por todo lo que le pasaba a Mileva. Sin embargo, ahora creo  que lo que vivieron no fue premeditado por él, sino consecuencias de las decisiones que ella tomó y de las expectativas que puso en Einstein. Mileva tenía problemas de autoestima severos y al sentirse querida y \"merecida\" dejó que otro decidiera por ella. Eso pasa muchísimo, la minimización de nuestras habilidades y la necesidad de que estas sean percibidas por el otro para validarlas. (También creo que Einstein no quería hijos, a pesar de que los amó, creo que para él el conocimiento era más importante que la familia?\nPerdimos una gran científica en ese entonces. ¿Cuántas habremos perdido por lo mismo?\nTotalmente recomendado este libro"
},
{
"t": "Donde cantan las ballenas",
"a": "Sara Jaramillo Klinkert",
"s": 3,
"y": 2022,
"p": 368,
"i": 57664985,
"c": 1,
"d": "2022-03-14",
"o": 2021,
"e": "Lumen"
},
{
"t": "Días sin ti",
"a": "Elvira Sastre",
"s": 5,
"y": 2022,
"p": 264,
"i": 44146624,
"c": 1,
"d": "2022-03-06",
"o": 2019,
"e": "Seix Barral"
},
{
"t": "Largo pétalo de mar",
"a": "Isabel Allende",
"s": 5,
"y": 2022,
"p": 375,
"i": 44660715,
"c": 1,
"d": "2022-02-28",
"o": 2019,
"e": "Plaza & Janés"
},
{
"t": "Una suerte pequeña",
"a": "Claudia Piñeiro",
"s": 5,
"y": 2022,
"p": 240,
"i": 25437388,
"c": 1,
"d": "2022-02-10",
"o": 2015,
"e": "Alfaguara"
},
{
"t": "La mujer justa",
"a": "Sándor Márai",
"s": 3,
"y": 2022,
"p": 416,
"i": 71468,
"c": 1,
"d": "2022-02-06",
"o": 1941,
"e": "SALAMANDRA"
},
{
"t": "Stoner",
"a": "John Williams",
"s": 4,
"y": 2022,
"p": 305,
"i": 8551582,
"c": 1,
"d": "2022-01-07",
"o": 1965,
"e": "NYRB Classics",
"r": "Es el libro más simple que he leído. Y escribo simple sin el ánimo de ofender al escritor. Me refiero a simple porque no trata en ningún momento de embellecer la vida del protagonista, William Stoner. Un profesor de literatura. Alguien que no sobresalió nunca, y que al momento de morir, su recuerdo quedó olvidado en un estante de la biblioteca de la Universidad. En un libro, escrito por él, en sus años de academia. En este libro no gana nadie. Ni Stoner, ni la esposa, ni la hija. La vida les pasó muchas facturas. \n\nEs raro leer la rutina de alguien. Los numerosos momentos que no trascienden, que no significan nada. Acostumbrada a que siempre queremos colorear la vida, Stoner permite disfrutarla tal y como es. Simple y cotidiana"
},
{
"t": "Arráncame La Vida",
"a": "Ángeles Mastretta",
"s": 4,
"y": 2021,
"p": 306,
"i": 41039266,
"c": 1,
"d": "2021-11-27",
"o": 1985,
"e": "Planeta Deagostini"
},
{
"t": "Alguien tiene que llevar la contraria",
"a": "Alejandro Gaviria",
"s": 3,
"y": 2021,
"p": 165,
"i": 32850547,
"c": 1,
"d": "2021-10-31",
"o": 2016,
"e": "Ariel Colombia"
},
{
"t": "El libro de los abrazos",
"a": "Eduardo Galeano",
"s": 3,
"y": 2021,
"p": 272,
"i": 40801886,
"c": 1,
"d": "2021-10-23",
"o": 1989,
"e": "Siglo MX"
},
{
"t": "La ridícula idea de no volver a verte",
"a": "Rosa Montero",
"s": 3,
"y": 2021,
"p": 223,
"i": 19086601,
"c": 1,
"d": "2021-10-23",
"o": 2013,
"e": "Seix Barral"
},
{
"t": "Find Me",
"a": "André Aciman",
"s": 5,
"y": 2021,
"p": 273,
"i": 45448146,
"c": 1,
"d": "2021-10-13",
"o": 2019,
"e": "Farrar, Straus and Giroux",
"r": "Hay muchos géneros en la literatura. Mi favorito es la novela, y es que leer historias me transporta a lo que siente y experimenta el protagonista. Creo que todas las historias bien podrían estar pasando en este momento a alguien en alguna parte del mundo,  somos tantos con vidas tan diferentes que me parece tremenda proeza que los escritores imaginen y escriban fragmentos de vida.\n\nPensé en \"Find me\" durante  todo el tiempo que me tardé en leerlo. Pensaba lo que Elio estaba sintiendo y viviendo, como una espectadora de su vida. Esto lo hace un excelente libro, al menos para mí gusto. El amor se vive de formas tan diferentes y leer algunas es tremendo parche. Así que recomiendo este libro. Si se ven la primera parte en película (Call me by your name) pueden ponerle rostro a los personajes lo cual lo hace más entretenido."
},
{
"t": "El amor en los tiempos del cólera",
"a": "Gabriel García Márquez",
"s": 5,
"y": 2021,
"p": 461,
"i": 500400,
"c": 1,
"d": "2021-10-12",
"o": 1985,
"e": "Vintage Español"
},
{
"t": "Angosta",
"a": "Héctor Abad Faciolince",
"s": 5,
"y": 2021,
"p": 374,
"i": 1755359,
"c": 1,
"d": "2021-10-03",
"o": 2003,
"e": "Planeta"
},
{
"t": "Call Me By Your Name",
"a": "André Aciman",
"s": 4,
"y": 2021,
"p": 256,
"i": 43985193,
"c": 1,
"d": "2021-09-05",
"o": 2007,
"e": "Farrar, Straus and Giroux"
},
{
"t": "Amplitud",
"a": "David Epstein",
"s": 3,
"y": 2021,
"p": 352,
"i": 53604522,
"c": 0,
"d": "2021-08-08",
"o": 2019,
"e": "Empresa Activa"
},
{
"t": "En busca de Venus. El arte de medir el cielo",
"a": "Andrea Wulf",
"s": 5,
"y": 2021,
"p": 396,
"i": 50096588,
"c": 0,
"d": "2021-08-01",
"o": 2012,
"e": "Taurus",
"r": "Es mi segundo libro de Andrea Wulf y de nuevo he quedado encantada. Detrás de los datos que ahora se dan en las clases de ciencias hay una historia increíble de científicos que sacrificaron hasta sus vidas para obtener datos lo más exactos posibles.\n\nAndrea escribe de tal manera que un tema, que puede ser aburrido para los que no somos astrónomos o que no nos interesa tanto, llegue a ser un historia interesante de principio a fin y sumemosle a esto que toda la información se sustenta de una basta búsqueda bibliográfica."
},
{
"t": "La isla",
"a": "Aldous Huxley",
"s": 3,
"y": 2021,
"p": 573,
"i": 3234781,
"c": 0,
"d": "2021-07-18",
"o": 1962,
"e": "Editora y Distribuidora Hispano Americana, S.A."
},
{
"t": "Todos deberíamos ser feministas",
"a": "Chimamanda Ngozi Adichie",
"s": 5,
"y": 2021,
"p": 32,
"i": 26529549,
"c": 1,
"d": "2021-07-11",
"o": 2012,
"e": "Literatura Random House",
"r": "Es un ensayo corto y prufundo, que nos permite evaluar nuestra conducta y nuestra forma de abordar el feminismo.\n\nActualmente, con toda la descarga de información que nos llega por las redes sociales, hemos transformado el ser feminista a salir desnudas a la calle, hasta he visto mujeres que se sacan la copa menstrual en frente de todos. Me pregunto qué cambios de fondo se están generando en la colectividad. Que al final, eso es lo que necesitamos.\nNecesitamos que la sociedad en general vea al género femenino como igual. Que se nos permita alcanzar todas las estratificaciones sociales sin minimizarnos. Y para eso, veo la crianza como un arma poderosa de transformación y concuerdo totalmente con Chimamanda.\nAsí que recomiendo este libro como un \"se debe leer\"."
},
{
"t": "Manual de tolerancia",
"a": "Héctor Abad Gómez",
"s": 5,
"y": 2021,
"p": 155,
"i": 38354734,
"c": 1,
"d": "2021-06-30",
"o": 1988,
"e": "Angosta Editores",
"r": "Somos el olvido que seremos. Sin embargo, nuestro legado a través del arte, de la escritura o del amor permite que los que somos trascienda más allá del olvido de la muerte. Héctor Gómez fue un ser humano increíble, noble, amoroso, compasivo, transformador, con un optimismo envidiable y este libro permite que leamos su punto de vista sobre política, educación y salud. \n\nEste libro es un manual que nos permite parar y repensar nuestra conducta, nuestro acto de vivir. Es un libro que todos deberíamos tener y repasar de vez en cuando. Es un libro muy bello."
},
{
"t": "El club de las 5 de la mañana",
"a": "Robin Sharma",
"s": 1,
"y": 2021,
"p": 385,
"i": 42744102,
"c": 1,
"d": "2021-06-30",
"o": 2018,
"e": "GRIJALBO",
"r": "He leído varios libros de autoayuda y creo que este es el último. Su historia para \"entretener\" es aburrida y poco creíble. \nNo me dieron ganas de ser parte del club de las 5 am y creo que su esquema de vida no me gustaría aplicarlo en su totalidad. \n\nAl final de la lectura concluí  que no es un libro que recomendaría ni leer ni comprar así sea un best seller."
},
{
"t": "Después de la ira",
"a": "Cristian Romero",
"s": 3,
"y": 2021,
"p": 133,
"i": 39713198,
"c": 1,
"d": "2021-05-27",
"o": 2018,
"e": "Alfaguara",
"r": "Detrás de cada historia podemos aprender o entender algo nuevo. Siempre (al menos creo yo). Y con este libro visualicé lo que puede pasar cuando las empresas llegan a los pueblos a imponer un solo tipo de negocio y acaba con todo lo demás. Cristian narra como una multinacional que cultiva maíz transgénico afecta la vida de un pueblo. Sus habitantes (agricultores) vendieron sus tierras y los que no, se enfrentaron a la contaminación de los suelos y al poco mercado de sus productos. Y aunque no estoy en contra de la modificación genética (soy biotecnóloga) si estoy en contra de la invasión imperialista (no pude evitar decirlo jaja). mentiras, estoy en contra de la forma tan incorrecta como nos monopolizan y cambian las leyes sin importar el impacto ambiental o social que puedan producir. Sabían por ejemplo que en Colombia solo se puede comprar semillas certificadas, al igual que en USA, y que estas semillas necesitan ciertos químicos específicos. Poco a poco perdemos la biodiversidad y tema que poco hemos hecho para evitarlo. En fin, volviendo al libro, El autor narra la historia de varias personas del pueblo y toda su dinámica alrededor de la multinacional, Cristian utiliza cambios de tiempo en cada capitulo que para mi fueron entretenidos. Al final, quedé con ganas de más historia, de otras 135 pag de ahondar la vida de ellos."
},
{
"t": "Siquiera tenemos las palabras",
"a": "Alejandro Gaviria",
"s": 3,
"y": 2021,
"p": 224,
"i": 44795150,
"c": 1,
"d": "2021-05-20",
"o": 2019,
"e": "Ariel",
"r": "Con tanta farándula para que se lance de candidato presidencial consideré pertinente leer sus libros. y me ha gustado mucho. La política y la gobernabilidad es algo complejo de entender y  tendemos a la generalización con el \"nunca hacen nada\" y creo que nunca es el caso (ni siquiera con los corruptos) . Ya este es el segundo libro que leo de Gaviria y utiliza el mismo estilo. Toma pensamientos y escritos de diversas personas para exponer su punto de vista. En este caso habló de Borges, Conrad, Stanislaw Lem, Orwell, Vargas Llosa, entre otros. Y escribió sobre la felicidad, la corrupción del lenguaje, la memoria, la política y el optimismo moderado. y como dice en la introducción, \"vivimos en una época inquietante y contradictoria pero siquiera tenemos las palabras. La literatura no podrá salvarnos, pero es uno de nuestros principales mecanismos de defensa; un refugio, un consuelo y una forma de resistencia\"."
},
{
"t": "Cartas a Antonia",
"a": "Alfredo Molano Bravo",
"s": 3,
"y": 2021,
"p": 286,
"i": 54867068,
"c": 0,
"d": "2021-04-26",
"o": 2020,
"e": "AGUILAR",
"r": "Ojalá todos tuviéramos la costumbre de escribir nuestra vida, el día a día. Alfredo lo hizo para su nieta. En esas pequeñas cartas contaba banalidades y a la vez le dejaba un consejo. El libro me llevó a conocer diversas regiones de la Colombia rural, me dejó ver una historia familiar y el amor puro de un abuelo a su nieta.\n\nEn la última parte, él escribe toda su experiencia con el cáncer y con el no querer morir, en el vacío que sentirá Antonia y él al ya no estar. Es triste saber que no quería morir, que todavía quería hacer muchas cosas y que su mente no estaba lista para partir."
},
{
"t": "Cuando éramos felices pero no lo sabíamos",
"a": "Melba Escobar",
"s": 2,
"y": 2021,
"p": 309,
"i": 55983672,
"c": 0,
"d": "2021-04-15",
"o": 2020,
"e": "Seix Barral Colombia",
"r": "Dos cosas me llevaron a comprar este libro. La portada y Venezuela. Al crecer en la frontera vi los cambios graduales que se fueron presentando en el día a día y como paulatinamente la gente empezó a cambiar sus rutinas y costumbres hasta que ya no hubo vuelta atrás. De pronto no pensaron que las cosas iban a transformarse de esta manera. No es así cómo pensamos todos?.\n\nLa autora hizo 4 viajes a Venezuela. Los tres relatos iniciales me parecieron superfluos y llenos de fastidio. Preguntas y respuestas banales, nada de análisis, miedo y ganas de salir de ahí. Solo en el último leí mejores preguntas, respuestas y una perspectiva más analítica. Cuál fue la diferencia? Me parece que consistió en qué en ese último viaje se tenía la compañía de conocidos lo cual hizo su viaje más paseo que viaje periodístico. El libro tiene algunos pedacitos cheveres pero no me gustó tanto."
},
{
"t": "El ego es el enemigo",
"a": "Ryan Holiday",
"s": 4,
"y": 2021,
"p": 249,
"i": 37703996,
"c": 1,
"d": "2021-04-13",
"o": 2016,
"e": "Paidos Empresa Colombia",
"r": "Todos tenemos una temporada de autoreconocimiento. Es decir, evaluamos nuestra vida, nuestras ideas y nuestras acciones. Es en este momento, para mí, el mejor para leer este tipo de libros. Ryan a través de este libro nos lleva a evaluar nuestras acciones y analizar sobre qué idea están sustentadas y de pronto por qué no, modificarlas y darles una nueva resignificación. \nAsi que si usted al igual que yo se encuentra en el autoreconocimiento, no dude en el leer este libro"
},
{
"t": "Las razones del amor",
"a": "Harry G. Frankfurt",
"s": 4,
"y": 2021,
"p": 128,
"i": 3500,
"c": 1,
"d": "2021-04-10",
"o": 2004,
"e": "Ediciones Paidós",
"r": "Creo que es mi segundo libro de filosofía. Lo leí por recomendación de un podcast llamado urbi et Orbi (recomendado).\n\nFrankfurt nos lleva a analizar tres puntos. Cómo vivir, las razones del amor y el amor propio. Y, me quedé con lo siguiente:\n\nEs importante vivir bajo los criterios ue hemos considerado importantes y que nos importan a nosotros. Por lo tanto, juzgar los criterios de los otros es innecesario e imposible porque no hay como definir cuáles criterios son buenos o malos y bajo cuál parámetro juzgar.\n\nEl amor es desinteresado e incluye amar lo que el amado ama y le importa. Por lo tanto, es importante que los dos amén o les importe las mismas cosas (en su mayoría) \n\nEl amor propio es sumamente importante y es uno de los amores más puros. \n\nSi no leen tanta filosofía, como yo. Les recomiendo escuchar el podcast y en específico el  capítulo sobre el amor."
},
{
"t": "El olvido que seremos",
"a": "Héctor Abad Faciolince",
"s": 5,
"y": 2021,
"p": 319,
"i": 1043247,
"c": 1,
"d": "2021-03-06",
"o": 2006,
"e": "Planeta Columbiana"
},
{
"t": "Medio sol amarillo",
"a": "Chimamanda Ngozi Adichie",
"s": 5,
"y": 2021,
"p": 544,
"i": 34687485,
"c": 1,
"d": "2021-03-06",
"o": 2006,
"e": "Literatura Random House"
},
{
"t": "El maestro y Margarita",
"a": "Mikhail Bulgakov",
"s": 3,
"y": 2021,
"p": 486,
"i": 4101800,
"c": 1,
"d": "2021-02-14",
"o": 1967,
"e": "Alianza"
},
{
"t": "Otro fin del mundo es posible",
"a": "Alejandro Gaviria",
"s": 3,
"y": 2021,
"p": 143,
"i": 55597480,
"c": 0,
"d": "2021-01-25",
"o": 2020,
"e": "Editorial Planeta",
"r": "Me gustó conocer las ideas de huxley y cómo cambiaron a través de los años y cómo plasmó esas ideas en sus dos libros más importantes, un mundo feliz y la isla, sin embargo, quedé con la falta de análisis de Gaviria. Esperaba más ideas de él o al menos un análisis de ese otro final del mundo.\nEs un libro para subrayar, para buscar esos párrafos en los libros de huxley y quedé con las ganas y la intención de leer la isla."
},
{
"t": "Río Muerto",
"a": "Ricardo Silva Romero",
"s": 4,
"y": 2021,
"p": 156,
"i": 53486677,
"c": 0,
"d": "2021-01-20",
"o": 2020,
"e": "Alfaguara",
"r": "Ricardo en este libro cuenta una de las historias a que se repiten muchas veces en Colombia. Pueblos olvidados por el gobierno y corrupción. Leer este tipo de libros es necesario para que todos hablemos de cómo podemos aportar a la paz."
},
{
"t": "Historia mínima de Colombia",
"a": "Jorge Orlando Melo",
"s": 4,
"y": 2021,
"p": 0,
"i": 39187008,
"c": 1,
"d": "2021-01-14",
"o": 2018,
"e": "Colegio de México",
"r": "Nos enseñan en el colegio nuestra historia sin embargo, en ese momento posiblemente no tenemos la capacidad de darle la importancia que se merece. Por esto, creo que este libro que recopila desde la conquista hasta nuestros tiempos es importante leerlo cuando ya tenemos la madurez para analizar y entender nuestra realidad."
},
{
"t": "Kilómetro Cero",
"a": "Leonardo Padrón",
"s": 4,
"y": 2021,
"p": 202,
"i": 17980275,
"c": 1,
"d": "2021-01-09",
"o": 2013,
"e": "Editorial Planeta Venezolana",
"r": "Quedé con ganas de leer a más escritores venezolanos y con la inquietud de conocer que sintieron en los comienzos del gobierno de Chávez."
},
{
"t": "The Invention of Nature",
"a": "Andrea Wulf",
"s": 5,
"y": 2020,
"p": 473,
"i": 23995249,
"c": 1,
"d": "2020-12-31",
"o": 2015,
"e": "Knopf",
"r": "Me encantó"
},
{
"t": "Historia oficial del amor",
"a": "Ricardo Silva Romero",
"s": 4,
"y": 2020,
"p": 540,
"i": 30071049,
"c": 1,
"d": "2020-10-21",
"o": 2016,
"e": "Alfaguara",
"r": "Me encantó como el contexto de Colombia moldeó la familia de Ricardo. Seguramente nuestras familias pasaron por cosas similares pero no nos hemos tomado el tiempo para preguntar."
},
{
"t": "El proyecto esposa",
"a": "Graeme Simsion",
"s": 0,
"y": null,
"p": 315,
"i": 18769932,
"c": 1,
"o": 2013,
"e": "Salamandra",
"r": "Aunque el nombre del libro no es muy interesante, está historia es muy entretenida y ligera"
},
{
"t": "Brave New World and Brave New World Revisited",
"a": "Aldous Huxley",
"s": 5,
"y": null,
"p": 340,
"i": 5479,
"c": 1,
"o": 1932,
"e": "Harper Perennial Modern Classics"
},
{
"t": "El mundo de Sofía",
"a": "Jostein Gaarder",
"s": 0,
"y": null,
"p": 638,
"i": 1212515,
"c": 1,
"o": 1991,
"e": "Ediciones Siruela, S.A."
},
{
"t": "El color de las cosas invisibles",
"a": "Andrea Longarela",
"s": 5,
"y": null,
"p": 512,
"i": 136078054,
"c": 1,
"o": 2023,
"e": "Crossbooks"
},
{
"t": "The Love Hypothesis",
"a": "Ali Hazelwood",
"s": 4,
"y": null,
"p": 373,
"i": 56732449,
"c": 1,
"o": 2021,
"e": "Berkley Books"
},
{
"t": "La teoría del amor",
"a": "Ali Hazelwood",
"s": 4,
"y": null,
"p": 436,
"i": 141869624,
"c": 1,
"o": 2023,
"e": "Contraluz Editorial",
"r": "En los momentos difíciles me decanto por estos libros. Se leen rápido, emocionan rápido y salen rápido de mi mente. Me causa curiosidad que este tipo de libro son best sellers sin dudarlo. Un hombre con problemas pero no tan graves, apuesto, que no se ha enamorado nunca, inteligente y súper guapo. Un cliché perfecto. Sin embargo, la autora escribe un ambiente que no es común y es el de l vida de los científicos. Es aterrizar que detrás de los artículos y fotos acartonadas también tenemos una vida. Y eso me parece perfecto. \n\nEso si, no quita que me cansa que el hombre sea el proveedor, El Fuerte, al que le va mejor. Y la protagonista sea menor que él y tenga mil mierdas por resolver. Así ves la historia perfecta de amor Ali Hazelwood?. Ojalá se saliera de ese esquema tan repetitivo de sus libros. \n\nDe resto gracias. Una historia que necesitaba en este punto de mi vida. Siempre que termino de leerte me dan ganas de volver a la academia, de ser parte de ese alboroto, así que eso lo llamo un éxito editorial jaja"
},
{
"t": "Below Zero",
"a": "Ali Hazelwood",
"s": 0,
"y": null,
"p": 112,
"i": 59651553,
"c": 0,
"o": 2022,
"e": "Berkley"
},
{
"t": "Lo que no tiene nombre",
"a": "Piedad Bonnett",
"s": 5,
"y": null,
"p": 130,
"i": 17565948,
"c": 1,
"o": 2013,
"e": "Alfaguara, S.A."
},
{
"t": "El último encuentro",
"a": "Sándor Márai",
"s": 2,
"y": null,
"p": 192,
"i": 71464,
"c": 1,
"o": 1942,
"e": "Planeta Publishing"
},
{
"t": "El Evangelio según Jesucristo",
"a": "José Saramago",
"s": 4,
"y": null,
"p": 496,
"i": 769660,
"c": 1,
"o": 1991,
"e": "Punto de Lectura S.L."
},
{
"t": "Brave New World",
"a": "Aldous Huxley",
"s": 5,
"y": null,
"p": 288,
"i": 5129,
"c": 1,
"o": 1932,
"e": "HarperPerennial / Perennial Classics"
},
{
"t": "Romeo and Juliet",
"a": "William Shakespeare",
"s": 4,
"y": null,
"p": 281,
"i": 18135,
"c": 1,
"o": 1590,
"e": "Washington Square Press"
},
{
"t": "Alice’s Adventures in Wonderland / Through the Looking-Glass",
"a": "Lewis Carroll",
"s": 5,
"y": null,
"p": 239,
"i": 24213,
"c": 1,
"o": 1871,
"e": "Penguin Group (USA)"
},
{
"t": "Memoirs of a Geisha",
"a": "Arthur Golden",
"s": 4,
"y": null,
"p": 503,
"i": 929,
"c": 1,
"o": 1997,
"e": "Vintage Books USA"
},
{
"t": "Twilight",
"a": "Stephenie Meyer",
"s": 3,
"y": null,
"p": 544,
"i": 41865,
"c": 1,
"o": 2005,
"e": "Little, Brown and Company"
},
{
"t": "To Kill a Mockingbird",
"a": "Harper Lee",
"s": 0,
"y": null,
"p": 323,
"i": 2657,
"c": 1,
"o": 1960,
"e": "Harper Perennial Modern Classics "
},
{
"t": "The Da Vinci Code",
"a": "Dan Brown",
"s": 4,
"y": null,
"p": 489,
"i": 968,
"c": 1,
"o": 2003,
"e": "Anchor"
},
{
"t": "The Alchemist",
"a": "Paulo Coelho",
"s": 3,
"y": null,
"p": 182,
"i": 18144590,
"c": 1,
"o": 1988,
"e": "HarperOne"
},
{
"t": "Little Women",
"a": "Louisa May Alcott",
"s": 5,
"y": null,
"p": 449,
"i": 1934,
"c": 1,
"o": 1868,
"e": "Signet Classics"
},
{
"t": "1984",
"a": "George Orwell",
"s": 5,
"y": null,
"p": 298,
"i": 40961427,
"c": 1,
"o": 1949,
"e": "Houghton Mifflin Harcourt"
},
{
"t": "Orgullo y prejuicio",
"a": "Jane Austen",
"s": 5,
"y": null,
"p": 544,
"i": 110815,
"c": 1,
"o": 1813,
"e": "Punto de Lectura"
},
{
"t": "The Analyst",
"a": "John Katzenbach",
"s": 5,
"y": null,
"p": 491,
"i": 67931,
"c": 1,
"o": 2002,
"e": "Corgi"
},
{
"t": "El túnel",
"a": "Ernesto Sabato",
"s": 3,
"y": null,
"p": 158,
"i": 53447,
"c": 1,
"o": 1948,
"e": "Booket"
},
{
"t": "Perfume: The Story of a Murderer",
"a": "Patrick Süskind",
"s": 5,
"y": null,
"p": 263,
"i": 343,
"c": 1,
"o": 1985,
"e": "Penguin Books"
},
{
"t": "The Catcher in the Rye",
"a": "J.D. Salinger",
"s": 1,
"y": null,
"p": 277,
"i": 5107,
"c": 1,
"o": 1951,
"e": "Back Bay Books"
},
{
"t": "Fifty Shades of Grey",
"a": "E.L. James",
"s": 5,
"y": null,
"p": 356,
"i": 10818853,
"c": 1,
"o": 2011,
"e": "Vintage"
},
{
"t": "Angels & Demons",
"a": "Dan Brown",
"s": 5,
"y": null,
"p": 736,
"i": 960,
"c": 1,
"o": 2000,
"e": "Pocket Books"
},
{
"t": "The Maze Runner",
"a": "James Dashner",
"s": 5,
"y": null,
"p": 384,
"i": 6186357,
"c": 1,
"o": 2009,
"e": "Delacorte Press"
},
{
"t": "Foundation and Empire",
"a": "Isaac Asimov",
"s": 5,
"y": null,
"p": 256,
"i": 29581,
"c": 1,
"o": 1952,
"e": "Spectra"
},
{
"t": "Mockingjay",
"a": "Suzanne Collins",
"s": 5,
"y": null,
"p": 392,
"i": 7260188,
"c": 1,
"o": 2010,
"e": "Scholastic Press"
},
{
"t": "Catching Fire",
"a": "Suzanne Collins",
"s": 5,
"y": null,
"p": 391,
"i": 6148028,
"c": 1,
"o": 2009,
"e": "Scholastic Press"
},
{
"t": "Foundation",
"a": "Isaac Asimov",
"s": 5,
"y": null,
"p": 244,
"i": 29579,
"c": 1,
"o": 1951,
"e": "Bantam"
},
{
"t": "The Hunger Games",
"a": "Suzanne Collins",
"s": 5,
"y": null,
"p": 374,
"i": 2767052,
"c": 1,
"o": 2008,
"e": "Scholastic Press"
},
{
"t": "Fahrenheit 451",
"a": "Ray Bradbury",
"s": 5,
"y": null,
"p": 249,
"i": 13079982,
"c": 1,
"o": 1963,
"e": "Simon & Schuster"
},
{
"t": "Cien años de soledad",
"a": "Gabriel García Márquez",
"s": 5,
"y": null,
"p": 747,
"i": 370523,
"c": 1,
"o": 1967,
"e": "Alfaguara",
"r": "Creo que había planeado leerlo desde hace mucho tiempo pero nunca lo hice. Así que al hacerlo siendo una adulta me pareció muy entretenido. Al final vemos que la desicion de Aureliano y Ursula de casarse siendo \"familiares\" conllevo al fracaso familiar de muchas generaciones. Gabriel escribió una historia muy bonita de leer, donde las líneas de tiempo a veces son borrososas y se entremezclan. Recomendado."
}
];
